#!/bin/sh -Cue
#.help
# % CMD..
#
# Manage ~/.hg symlink to .home-hg while running the given Mercurial command.
#
# Run CMD hhg-activate to keep the symlink until running hhg-release.

fatal() { rc="$1"; shift; printf %s\\n "${0##*/} error: $*" >&2 || true; exit "$rc"; }
nonfatal() { printf %s\\n "${0##*/}: $*" >&2 || true; }

while [ $# -gt 0 ]; do case "$1" in --) shift; break ;; -) break ;; -*) fatal 64 'unexpected option' ;; *) break ;; esac; done

if [ ! -L ~/.hg -a -e ~/.hg ]; then
    fatal 65 "~/.hg exists and is not a symlink"
    fi
[ -e ~/.home-hg ] || fatal 65 'missing ~/.home-hg'
[ $# != 0 ] || exec hg
cmd="$(dirname "$(readlink -f -- "$0")")"
case "$1" in
    hhg-*)
        [ -e "$cmd/$1" ] || fatal 64 "bad command: $1"
        exec "$cmd/$@"
        ;;
    esac

"$cmd/hhg-check"
"$cmd/hhg-activate"
trap '"$cmd/hhg-release"' exit
hg "$@"
